src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # NOQA: F401
from django.conf.urls.static import static  # NOQA: F401

from basic.authentication_views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    send_test_email,
    ActivateUserViews,
)
from basic.views import UserProfileDetailView, UserProfileListView, UpdateUserProfileView
from students.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("", IndexView.as_view(), name="index"),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("activate/<str:uuid64>/<str:token>", ActivateUserViews.as_view(), name="activate_user"),
    path("user_profile/<int:pk>", UserProfileDetailView.as_view(), name="user_profile"),
    path("user_profile_list", UserProfileListView.as_view(), name="user_profile_list"),
    path("update_user_profile/<int:pk>", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "students.views.handling_404"

src/groups/urls.py
from django.contrib import admin  # NOQA: F401
from django.urls import path

from groups.views import get_groups, info_group, GroupCreateView, GroupUpdateView, GroupDeleteView

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_groups"),
    path("create_group/", GroupCreateView.as_view(), name="create_group"),
    path("update_group/<uuid:uuid>", GroupUpdateView.as_view(), name="update_group"),
    path("delete_group/<uuid:uuid>", GroupDeleteView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", info_group, name="info_group"),
]

src/students/urls.py
from django.urls import path
from students.views import get_student, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", get_student, name="get_student"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>", DeleteStudentView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import get_teachers, CreateTeacherView, DeleteTeacherView, UpdateTeacherView

app_name = "teachers"

urlpatterns = [
    path("", get_teachers, name="get_teachers"),
    path("create_teachers/", CreateTeacherView.as_view(), name="create_teachers"),
    path("update_teachers/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete_teachers/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/templates/index.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">

    <title>Headers · Bootstrap v5.0</title>

    <link rel="canonical" href="{% static 'css/user_profile_style.css' %}">
    {#    <link rel="gsi-material-button" href="{% static 'css/google_button.css' %}">#}


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/headers.css' %}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'index' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'main/img/LMS.png' %}" alt="student image" width="50" height="50">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'index' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                <li><a href="/admin" class="nav-link px-2 text-white">About</a></li>
            </ul>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form>

            <div class="text-end">
                {% if user.is_authenticated %}
                    <span>{{ user.username }}</span>

                    {% if user.photo %}
                        <img src="{{ user.photo }}" width="50" height="50">
                    {% else %}
                        <img src="{% static 'main/img/user.png' %}" width="50" height="50">
                    {% endif %}
                    <a href="{% url 'logout' %}" type="button" class="btn btn-light">Logout</a>
                {% else %}
                    <a href="{% url 'register' %}" type="button" class="btn btn-success">Registration</a>
                    <a href="{% url 'social:begin' 'google-oauth2' %}">
                        <img src="{% static 'main/img/google.jpg' %}" alt="Google" width="37.83" height="37.83">
                    </a>
{#                    <a href="{% url 'social:begin' 'facebook' %}" type="button" class="btn btn-success">Facebook</a>#}
                    <a href="{% url 'social:begin' 'facebook' %}">
                        <img src="{% static 'main/img/facebook.jpg' %}" alt="GitHub" width="37.83" height="37.83">
                    </a>
                    <a href="{% url 'social:begin' 'github' %}">
                        <img src="{% static 'main/img/github.jpg' %}" alt="GitHub" width="37.83" height="37.83">
                    </a>
                    <a href="{% url 'login' %}" type="button" class="btn btn-light">Login</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<main>
    {% block content %}
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <h1 class="fw-light">Album example</h1>
                    <p class="lead text-body-secondary">Something short and leading about the collection below—its
                        contents,
                        the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it
                        entirely.</p>
                    <p>
                        <a href="{% url 'students:create_student' %}" class="btn btn-primary">Create students</a>
                        <a href="{% url 'teachers:create_teachers' %}" class="btn btn-primary">Create teachers</a>
                        <a href="{% url 'groups:create_group' %}" class="btn btn-primary">Create groups</a>
                    </p>
                </div>
            </div>
        </section>

        <div class="album py-5 bg-body-tertiary">
            <div class="container">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                    <div class="col">
                        <div class="card shadow-sm h-100">
                            <img src="{% static 'student/img/20210121collegestudents.jpg' %}" alt="student image">
                            <div class="card-body">
                                <p class="card-text">This are our students.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'students:get_student' %}" class="btn btn-primary" role="button"
                                           style="margin-top: 40px">All students</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm h-100">
                            <img src="{% static 'teachers/img/ENtwvqMg.jpg' %}" alt="teachers image">
                            <div class="card-body">
                                <p class="card-text">This are our teacher </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'teachers:get_teachers' %}" class="btn btn-primary"
                                           role="button">All teachers</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{% static 'groups/img/grouping-student.jpg' %}" alt="groups image" width="250"
                                 height="250
">
                            <div class="card-body">
                                <p class="card-text">This are our groups</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'groups:get_groups' %}" groups class="btn btn-primary"
                                           role="button">All groups</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}
</main>

<footer class="text-body-secondary py-5" style="margin-top: 150px;">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="../getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/test.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ data }}</title>
</head>
<body>

</body>
</html>