src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # NOQA: F401
from django.conf.urls.static import static  # NOQA: F401

from basic.authentication_views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    send_test_email,
    ActivateUserViews,
)
from basic.views import UserProfileDetailView, UserProfileListView, UpdateUserProfileView
from students.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("", IndexView.as_view(), name="index"),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("activate/<str:uuid64>/<str:token>", ActivateUserViews.as_view(), name="activate_user"),
    path("user_profile/<int:pk>", UserProfileDetailView.as_view(), name="user_profile"),
    path("user_profile_list", UserProfileListView.as_view(), name="user_profile_list"),
    path("update_user_profile/<int:pk>", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "students.views.handling_404"

src/groups/urls.py
from django.contrib import admin  # NOQA: F401
from django.urls import path

from groups.views import get_groups, info_group, GroupCreateView, GroupUpdateView, GroupDeleteView

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_groups"),
    path("create_group/", GroupCreateView.as_view(), name="create_group"),
    path("update_group/<uuid:uuid>", GroupUpdateView.as_view(), name="update_group"),
    path("delete_group/<uuid:uuid>", GroupDeleteView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", info_group, name="info_group"),
]

src/groups/models.py
from uuid import uuid4

from django.db import models
from faker import Faker


class Group(models.Model):
    uuid = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    name_group = models.CharField(max_length=150, blank=True, null=True)
    classroom = models.PositiveSmallIntegerField(blank=True, null=True)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    weekday = models.CharField(max_length=20, blank=True, null=True)
    max_students = models.PositiveIntegerField(blank=True, null=True)

    @classmethod
    def generate_group(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            group = Group(
                name_group=faker.word(),
                classroom=faker.pyint(min_value=1, max_value=150),
                start_time=faker.time(pattern="%H:%M:%S"),
                end_time=faker.time(pattern="%H:%M:%S"),
                weekday=faker.date_time().strftime("%A"),
                max_students=faker.pyint(min_value=10, max_value=20),
            )
            group.save()

    def __str__(self) -> str:
        return (
            f"{self.pk} {self.name_group} {self.classroom} {self.start_time} "
            f"{self.end_time} {self.weekday} {self.max_students}"
        )

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["name_group", "classroom", "start_time", "end_time", "weekday", "max_students"]

src/groups/views.py
from uuid import uuid4

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView, DeleteView

from groups.forms import GroupForm
from groups.models import Group
from webargs import fields
from webargs.djangoparser import use_args


@login_required
@use_args(
    {
        "name_group": fields.Str(
            required=False,
        ),
        "start_time": fields.Time(
            required=False,
        ),
        "end_time": fields.Time(
            required=False,
        ),
        "search": fields.Str(
            required=False,
        ),
    },
    location="query",
)
def get_groups(request: HttpRequest, params) -> HttpResponse:
    groups = Group.objects.all()

    search_fields = ["name_group", "start_time", "end_time"]

    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            groups = groups.filter(or_filter)
        else:
            groups = groups.filter(**{param_name: param_value})

    return render(request, template_name="groups/templates/list_groups.html", context={"groups": groups})


class GroupCreateView(LoginRequiredMixin, CreateView):
    template_name = "groups/templates/create_groups.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "groups/templates/update_groups.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()
    pk_url_kwarg = "uuid"


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    fields = ["name_group", "classroom", "start_time", "end_time", "weekday", "max_students"]
    template_name = "groups/templates/delete_groups.html"
    queryset = Group.objects.all()
    success_url = reverse_lazy("groups:get_groups")
    pk_url_kwarg = "uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group = self.get_object()
        context["name_group"] = f"{group.name_group}"
        return context


@login_required
@csrf_exempt
def info_group(request: HttpRequest, uuid=uuid4) -> HttpResponse:
    group = get_object_or_404(Group.objects.all(), uuid=uuid)
    if request.method == "POST":
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            pass
    elif request.method == "GET":
        form = GroupForm(instance=group)
    return render(
        request, template_name="groups/templates/informations_about_groups.html", context={"form": form, "group": group}
    )

src/templates/groups/templates/create_groups.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/groups/templates/delete_groups.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Вы уверены, что хотите удалить группу {{ name_group }}?</h2>
    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock content %}

src/templates/groups/templates/informations_about_groups.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Group Information</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
        }
        .group-info {
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            max-width: 400px;
            margin: 0 auto;
        }
        .group-info h2 {
            margin-top: 0;
        }
        .group-info p {
            margin: 10px 0;
        }
        .edit-form {
            margin-top: 20px;
        }
        .edit-form label {
            display: block;
            margin-bottom: 5px;
        }
        .edit-form input[type="text"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }
        .edit-form input[type="submit"] {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .edit-form input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="group-info">
        <h2>Group Information</h2>
        <p><strong>Name:</strong> {{ group.name_group }}</p>
        <p><strong>Classroom:</strong> {{ group.classroom }}</p>
        <p><strong>Start Time:</strong> {{ group.start_time }}</p>
        <p><strong>End Time:</strong> {{ group.end_time }}</p>
        <p><strong>Weekday:</strong> {{ group.weekday }}</p>
        <p><strong>Max Students:</strong> {{ group.max_students }}</p>
    </div>
</body>
</html>

src/templates/groups/templates/list_groups.html
{% extends 'index.html' %}

{% block content %}
    <table class="table  table-striped ">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name group</th>
            <th scope="col">Classroom</th>
            <th scope="col">Start time</th>
            <th scope="col">End time</th>
            <th scope="col">Weekday</th>
            <th scope="col">Max students</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <th scope="row"> {{ group.pk }}</th>
                <td>{{ group.name_group }}</td>
                <td>{{ group.classroom }}</td>
                <td>{{ group.start_time }}</td>
                <td>{{ group.end_time }}</td>
                <td>{{ group.weekday }}</td>
                <td>{{ group.max_students }}</td>
                <td>
                    <a type="button" class="btn btn-success" href="{% url 'groups:update_group' group.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger" href="{% url 'groups:delete_group' group.pk %}">Delete</a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/groups/templates/update_groups.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-warning" value="Update">
    </form>
{% endblock content %}