src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # NOQA: F401
from django.conf.urls.static import static  # NOQA: F401

from basic.authentication_views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    send_test_email,
    ActivateUserViews,
)
from basic.views import UserProfileDetailView, UserProfileListView, UpdateUserProfileView
from students.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("", IndexView.as_view(), name="index"),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("activate/<str:uuid64>/<str:token>", ActivateUserViews.as_view(), name="activate_user"),
    path("user_profile/<int:pk>", UserProfileDetailView.as_view(), name="user_profile"),
    path("user_profile_list", UserProfileListView.as_view(), name="user_profile_list"),
    path("update_user_profile/<int:pk>", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "students.views.handling_404"

src/students/urls.py
from django.urls import path
from students.views import get_student, CreateStudentView, UpdateStudentView, DeleteStudentView

app_name = "students"

urlpatterns = [
    path("", get_student, name="get_student"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:uuid>", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:uuid>", DeleteStudentView.as_view(), name="delete_student"),
]

src/students/models.py
import os  # NOQA F401
from datetime import datetime
from uuid import uuid4

from django.db import models
from faker import Faker

from basic.models import Person
from groups.models import Group


class Student(Person):
    uuid = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    birth_date = models.DateField(blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    image_student = models.ImageField(blank=True, null=True, upload_to="static/student/img/")
    resume_student = models.FileField(blank=True, null=True, upload_to="static/student/pdf/")

    @classmethod
    def generate_student(cls, count: int) -> None:
        faker = Faker()
        groups = Group.objects.all()
        for i in range(count):
            student = Student.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=16, maximum_age=60),
                group=groups.first(),
            )
            student.save()

    def __str__(self) -> str:
        return f"{self.pk} {self.first_name} {self.last_name} {self.email} {self.birth_date} {self.image_student}"

    def age(self):
        return datetime.now().year - self.birth_date.year

src/students/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from groups.models import Group
from students.models import Student


# class StudentForm(ModelForm):
#     group = forms.ModelChoiceField(queryset=Group.objects.all(), to_field_name='name_group')
#
#     class Meta:
#         model = Student
#         fields = ["first_name", "last_name", "email", "group", "image_student", "resume_student"]


class StudentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        self.fields["group"].queryset = Group.objects.all()
        self.fields["group"].to_field_name = "name_group"
        self.fields["group"].label_from_instance = lambda obj: "%s" % obj.name_group

    group = forms.ModelChoiceField(queryset=Group.objects.none(), to_field_name="start_time")

    class Meta:
        model = Student
        fields = ["first_name", "last_name", "email", "group", "image_student", "resume_student"]

    @staticmethod
    def normalize_text(text):
        return text.strip().capitalize()

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex email is forbidden to use in our country")
        return email

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cannot be equal")
        return cleaned_data

src/students/views.py
from django import forms  # NOQA F401
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView

from students.models import Student

from webargs import fields
from webargs.djangoparser import use_args

from students.forms import StudentForm
from students.utils.formatters import format_records  # NOQA F401


class IndexView(TemplateView):
    template_name = "index.html"


@login_required
@use_args(
    {
        "first_name": fields.Str(
            required=False,
        ),
        "last_name": fields.Str(
            required=False,
        ),
        "search": fields.Str(
            required=False,
        ),
    },
    location="query",
)
def get_student(request: HttpRequest, params) -> HttpResponse:
    students = Student.objects.all()

    search_fields = ["first_name", "last_name", "email"]

    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            students = students.filter(or_filter)
        else:
            students = students.filter(**{param_name: param_value})
    return render(request, template_name="student/templates/list.html", context={"students": students})


class CreateStudentView(LoginRequiredMixin, CreateView):
    template_name = "student/templates/create.html"
    # model = Student
    # fields = ["first_name", "last_name", "email", "group", "image_student", "resume_student"]
    form_class = StudentForm
    success_url = reverse_lazy("students:get_student")


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    form_class = StudentForm
    template_name = "student/templates/update.html"
    queryset = Student.objects.all()
    success_url = reverse_lazy("students:get_student")
    pk_url_kwarg = "uuid"


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    fields = ["first_name", "last_name", "email", "group", "image_student", "resume_student"]
    template_name = "student/templates/delete.html"
    queryset = Student.objects.all()
    success_url = reverse_lazy("students:get_student")
    pk_url_kwarg = "uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student = self.get_object()
        context["student_name"] = f"{student.first_name} {student.last_name}"
        return context


@csrf_exempt
def handling_404(request: HttpRequest, exception: Exception) -> HttpResponse:
    return render(request, template_name="404.html")

src/templates/student/templates/create.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}4
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/student/templates/delete.html
{#{% extends 'index.html' %}#}
{#{% load crispy_forms_tags %}#}
{#{% block content %}#}
{#    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">#}
{#        {% csrf_token %}#}
{#        {{ form|crispy }}#}
{#        <input type="submit" class="btn btn-warning" value="Delete">#}
{#    </form>#}
{#{% endblock content %}#}

{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Вы уверены, что хотите удалить студента {{ student_name }}?</h2>
    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock content %}

src/templates/student/templates/list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <table class="table  table-striped ">
        <thead>
        <tr>
            <th scope="col">Student</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Grade</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Edit</th>
            <th scope="col">Resume</th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                {% if student.image_student %}
                    <th scope="row"><img src="{{ student.image_student.url }}" width="50" height="50"></th>
                {% else %}
                    <th scope="row"><img src="{% static 'student/img/free-icon-hacker-924915.png' %}" width="50"
                                         height="50"></th>
                {% endif %}
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.grade }}</td>
                {% if student.birth_date %}
                    <td>{{ student.birth_date }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}

                <td style="width: 150px;">
                    <a type="button" class="btn btn-success"
                       href="{% url 'students:update_student' student.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
                <td>
                    {% if student.resume_student %}
                        <a type="button" class="btn btn-info" href="{{ student.resume_student.url }}">Resume
                            PDF</a>
                    {% else %}
                         ---
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/student/templates/update.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-warning" value="Update">
    </form>
{% endblock content %}