src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # NOQA: F401
from django.conf.urls.static import static  # NOQA: F401

from basic.authentication_views import (
    UserLoginView,
    UserLogoutView,
    UserRegistrationView,
    send_test_email,
    ActivateUserViews,
)
from basic.views import UserProfileDetailView, UserProfileListView, UpdateUserProfileView
from students.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("", IndexView.as_view(), name="index"),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("activate/<str:uuid64>/<str:token>", ActivateUserViews.as_view(), name="activate_user"),
    path("user_profile/<int:pk>", UserProfileDetailView.as_view(), name="user_profile"),
    path("user_profile_list", UserProfileListView.as_view(), name="user_profile_list"),
    path("update_user_profile/<int:pk>", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "students.views.handling_404"

src/groups/urls.py
from django.contrib import admin  # NOQA: F401
from django.urls import path

from groups.views import get_groups, info_group, GroupCreateView, GroupUpdateView, GroupDeleteView

app_name = "groups"

urlpatterns = [
    path("", get_groups, name="get_groups"),
    path("create_group/", GroupCreateView.as_view(), name="create_group"),
    path("update_group/<uuid:uuid>", GroupUpdateView.as_view(), name="update_group"),
    path("delete_group/<uuid:uuid>", GroupDeleteView.as_view(), name="delete_group"),
    path("info/<uuid:uuid>", info_group, name="info_group"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import get_teachers, CreateTeacherView, DeleteTeacherView, UpdateTeacherView

app_name = "teachers"

urlpatterns = [
    path("", get_teachers, name="get_teachers"),
    path("create_teachers/", CreateTeacherView.as_view(), name="create_teachers"),
    path("update_teachers/<uuid:uuid>", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete_teachers/<uuid:uuid>", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
import random
from uuid import uuid4

from django.db import models
from faker import Faker

from basic.models import Person
from groups.models import Group


class Teacher(Person):
    uuid = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    years_of_experience = models.PositiveSmallIntegerField(blank=True, null=True)
    speciality = models.CharField(max_length=200, blank=True, null=True)
    group = models.ManyToManyField(Group)
    image_teacher = models.ImageField(blank=True, null=True, upload_to="static/teachers/img/")

    @classmethod
    def generate_teacher(cls, count: int) -> None:
        faker = Faker()
        group_queryset = Group.objects.all()[:3]
        group_list = list(group_queryset)
        for i in range(count):
            teacher = Teacher.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                salary=faker.pyfloat(
                    left_digits=None,
                    right_digits=2,
                    positive=True,
                    min_value=20000,
                    max_value=100000,
                ),
                years_of_experience=faker.pyint(min_value=1, max_value=15),
                speciality=faker.job(),
            )
            group_samples = random.sample(group_list, 2)
            teacher.group.set(group_samples)

    def __str__(self):
        return (
            f"{self.pk} {self.first_name} {self.last_name} {self.email} {self.years_of_experience} "
            f"{self.speciality} {self.salary} {self.years_of_experience} {self.speciality}"
        )

src/teachers/forms.py
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ["first_name", "last_name", "email", "years_of_experience", "speciality", "group", "image_teacher"]

src/teachers/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy

from django.views.generic import CreateView, UpdateView, DeleteView

from teachers.forms import TeacherForm
from teachers.models import Teacher

from webargs import fields
from webargs.djangoparser import use_args


@login_required
@use_args(
    {
        "first_name": fields.Str(
            required=False,
        ),
        "last_name": fields.Str(
            required=False,
        ),
        "salary": fields.Float(
            required=False,
        ),
        "search": fields.Str(required=False),
    },
    location="query",
)
def get_teachers(request: HttpRequest, params) -> HttpResponse:
    teachers = Teacher.objects.all()

    search_fields = ["first_name", "last_name", "salary"]

    for param_name, param_value in params.items():
        if param_name == "search":
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__contains": param_value})
            teachers = teachers.filter(or_filter)
        else:
            teachers = teachers.filter(**{param_name: param_value})
    return render(request, template_name="teachers/templates/list_teacher.html", context={"teachers": teachers})


class CreateTeacherView(LoginRequiredMixin, CreateView):
    template_name = "teachers/templates/create_teacher.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    template_name = "teachers/templates/update_teacher.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")
    queryset = Teacher.objects.all()
    pk_url_kwarg = "uuid"


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    template_name = "teachers/templates/delete_teacher.html"
    model = Teacher
    fields = ["first_name", "last_name", "email", "years_of_experience", "speciality", "group", "image_teacher"]
    queryset = Teacher.objects.all()
    success_url = reverse_lazy("teachers:get_teachers")
    pk_url_kwarg = "uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teacher = self.get_object()
        context["teacher_name"] = f"{teacher.first_name} {teacher.last_name}"
        return context

src/templates/teachers/templates/create_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Create">
    </form>
{% endblock content %}

src/templates/teachers/templates/delete_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2>Вы уверены, что хотите удалить учителя {{ teacher_name }}?</h2>
    <form method="post" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock content %}

src/templates/teachers/templates/list_teacher.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <table class="table  table-striped ">
        <thead>
        <tr>
            <th scope="col">Teacher</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Salary</th>
            <th scope="col">Years of experience</th>
            <th scope="col">Speciality</th>
            <th scope="col">Edit</th>
            <th scope="col">Group</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                {% if teacher.image_teacher %}
                    <th scope="row"><img src="{{ teacher.image_teacher.url }}" width="50" height="50"></th>
                {% else %}
                    <th scope="row"><img src="{% static 'teachers/img/img_2.png' %}" width="50" height="50"></th>
                {% endif %}
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.salary }}</td>
                <td>{{ teacher.years_of_experience }}</td>
                <td>{{ teacher.speciality }}</td>
                <td>
                    <a type="button" class="btn btn-success"
                       href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                    <a type="button" class="btn btn-danger"
                       href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                <td>
                    {% for group in teacher.group.all %}
                        <a type="button" class="btn btn-primary"
                           href="{% url 'groups:info_group' group.pk %}">{{ group.name_group }}</a>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/teachers/templates/update_teacher.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" enctype="multipart/form-data" style="width: 25em; margin: auto; margin-top: 100px;">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-warning" value="Update">
    </form>
{% endblock content %}